/**
 * Vendor the IBM Plex web fonts into `public/fonts` (§5.45).
 *
 * The product used to fetch its typeface from Google at runtime, which meant an air-gapped or
 * egress-restricted deployment — the sovereign case this product is aimed at — silently fell back
 * to the system stack and did not look like itself in the environment it is most meant for. It
 * also put a third-party request on every page load of an enterprise architecture tool.
 *
 * So the files are committed. This script is how they got there and how they are refreshed: it
 * asks Google's CSS API for the faces we use, downloads each woff2, and writes a plain stylesheet
 * pointing at the local copies. It runs on a developer's machine, never at build or boot.
 *
 *   node scripts/vendor-fonts.mjs
 *
 * The licence is committed alongside them: IBM Plex is SIL OFL 1.1, which permits redistribution.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const OUT = path.resolve("public/fonts");
const CSS = path.resolve("src/app/fonts.css");
const FAMILIES = "family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;700";
// Ask as a modern browser or the API answers with truetype rather than woff2.
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

mkdirSync(OUT, { recursive: true });

const res = await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, { headers: { "User-Agent": UA } });
if (!res.ok) throw new Error(`the font CSS answered ${res.status}`);
let css = await res.text();

const urls = [...new Set([...css.matchAll(/url\((https:\/\/[^)]+\.woff2)\)/g)].map((m) => m[1]))];
if (!urls.length) throw new Error("no woff2 files in the stylesheet");

let n = 0;
for (const url of urls) {
  const name = url.split("/").slice(-3).join("-").replace(/[^a-zA-Z0-9.-]/g, "_");
  const file = await fetch(url, { headers: { "User-Agent": UA } });
  if (!file.ok) throw new Error(`${url} answered ${file.status}`);
  writeFileSync(path.join(OUT, name), Buffer.from(await file.arrayBuffer()));
  css = css.split(url).join(`/fonts/${name}`);
  n++;
}

/*
 * `font-display: swap` on every face: text must be readable while the font loads, and a board full
 * of invisible card titles for 300ms is worse than a board that reflows once.
 */
css = css.replace(/font-display:\s*\w+;/g, "font-display: swap;");
/*
 * The rules go next to `globals.css` and are imported, not linked from the document: a hand-written
 * <link> is a second round trip before any text can be painted, and Next's own lint rule says so.
 * Only the font files themselves are static, under `public/fonts`.
 */
writeFileSync(CSS, `/* Generated by scripts/vendor-fonts.mjs — do not edit. IBM Plex, SIL OFL 1.1; the files are in public/fonts. */\n${css}`);
console.log(`${n} font files written to public/fonts, faces written to src/app/fonts.css`);
