import type { Provider } from "./types";

/**
 * The catalogue itself.
 *
 * Deliberately larger than what is built, and honest about which is which: an architecture
 * platform is judged on what it can reach, and a catalogue that hides its ambition is less
 * useful than one that says "planned" out loud. Every entry that reads through an API carries a
 * scope tree, because "connect SAP" is not a decision anybody should be asked to make — "read
 * Plant Maintenance equipment and functional locations, and nothing else" is.
 *
 * The scope trees are modelled on what these systems actually expose. They are the vocabulary of
 * the grant conversation, so they name the vendor's own objects (EQUI, cmdb_ci) rather than
 * inventing friendlier ones.
 */

export const PROVIDER_CATEGORIES: Array<{ id: Provider["category"]; name: string; detail: string }> = [
  { id: "conversations", name: "Conversations", detail: "What people said, wrote and decided" },
  { id: "files", name: "Files", detail: "Whatever is already on someone's disk" },
  { id: "systems", name: "Enterprise systems", detail: "Systems of record with an API" },
  { id: "repositories", name: "Code & data platforms", detail: "How the estate is actually built" },
  { id: "operations", name: "Operations & OT", detail: "The half of the estate that never had a CMDB" },
];

export const PROVIDERS: Provider[] = [
  // ---- conversations ----------------------------------------------------------------------
  {
    id: "transcript",
    name: "Meeting transcript",
    vendor: "Microsoft Teams · Zoom · Google Meet",
    category: "conversations",
    status: "available",
    mode: "upload",
    summary: "A transcript export: who said what, and what was decided.",
    rationale: "Most architecture knowledge is spoken before it is ever written down. A meeting names systems, assigns owners and settles direction weeks before any repository catches up.",
    auth: "No connection — the file is uploaded or pasted.",
    produces: "transcript",
    signals: [],
    fingerprints: [],
    scopes: [],
  },
  {
    id: "notes",
    name: "Notes & documents",
    vendor: "Any",
    category: "conversations",
    status: "available",
    mode: "upload",
    summary: "Minutes, strategy notes, architecture decision records.",
    rationale: "The written half of the same knowledge, usually more precise and always less current.",
    auth: "No connection — the file is uploaded or pasted.",
    produces: "document",
    signals: [],
    fingerprints: [],
    scopes: [],
  },
  {
    id: "email",
    name: "E-mail & chat",
    vendor: "Microsoft 365 · Slack",
    category: "conversations",
    status: "planned",
    mode: "api",
    summary: "Threads about a system, with the people and the timeline attached.",
    rationale: "Where decisions are actually revised. Also the most sensitive source in the catalogue, which is exactly why the scope is per-channel.",
    auth: "OAuth, delegated — the agent sees only what the granting user sees.",
    produces: "transcript",
    signals: ["outlook", "slack", "teams chat"],
    fingerprints: [
      { kind: "hostname", pattern: "\\b(?:teams|outlook)\\.(?:microsoft|office)\\.com\\b", weight: 3, note: "a Microsoft 365 collaboration host" },
      { kind: "hostname", pattern: "\\b[a-z0-9-]+\\.slack\\.com\\b", weight: 3, note: "a Slack workspace host" },
    ],
    scopes: [
      {
        path: "email/channels", name: "Named channels", description: "Specific Teams channels or Slack channels, chosen one by one.",
        yields: ["Discussion", "Decision", "Person"], enables: "Trace when a decision changed and who objected.",
        sensitivity: "confidential", volume: "per channel",
      },
      {
        path: "email/mailboxes", name: "Shared mailboxes", description: "Functional mailboxes (architecture@, servicedesk@), never personal ones.",
        yields: ["Discussion", "Request"], enables: "Catch the systems people ask about that no register lists.",
        sensitivity: "confidential", volume: "10k+ threads",
      },
    ],
  },

  // ---- files ------------------------------------------------------------------------------
  {
    id: "table",
    name: "CSV / JSON",
    vendor: "Any",
    category: "files",
    status: "available",
    mode: "upload",
    summary: "A structured list of entities and relations, mapped column by column.",
    rationale: "The application list that actually runs the organisation is usually a spreadsheet.",
    auth: "No connection — the file is uploaded or pasted.",
    produces: "table",
    signals: [],
    fingerprints: [],
    scopes: [],
  },
  {
    id: "excel",
    name: "Excel workbook",
    vendor: "Microsoft",
    category: "files",
    status: "planned",
    mode: "upload",
    summary: "Multi-sheet workbooks, with the sheet-to-kind mapping remembered.",
    rationale: "Registries live in workbooks long after somebody bought a tool to replace them.",
    auth: "No connection — the file is uploaded.",
    produces: "table",
    signals: [],
    fingerprints: [],
    scopes: [],
  },
  {
    id: "visio",
    name: "Visio / draw.io",
    vendor: "Microsoft · JGraph",
    category: "files",
    status: "planned",
    mode: "upload",
    summary: "Diagrams read as a graph rather than as a picture.",
    rationale: "Thousands of hours of modelling are trapped in shapes and connectors that no system can query.",
    auth: "No connection — the file is uploaded.",
    produces: "table",
    signals: [],
    fingerprints: [],
    scopes: [],
  },

  // ---- enterprise systems ------------------------------------------------------------------
  {
    id: "mcp",
    name: "Any MCP server",
    vendor: "Model Context Protocol",
    category: "systems",
    status: "available",
    mode: "api",
    summary: "A system that already speaks MCP — a CMDB, a wiki, a ticket tracker, a vendor's own server.",
    rationale: "The cheapest connector is the one nobody has to write. A system that speaks MCP can be asked directly, and what it answers goes through intake like any other document: read for claims, quoted, and reviewed by a person before anything reaches the model.",
    auth: "A URL, and a key if that server wants one. Set up under Settings → Connections.",
    produces: "document",
    signals: [],
    fingerprints: [],
    scopes: [],
  },
  {
    id: "sap",
    name: "SAP",
    vendor: "SAP SE",
    category: "systems",
    status: "planned",
    mode: "api",
    summary: "Modules, master data and the process footprint around them.",
    rationale: "In an asset-heavy organisation SAP *is* the operating model. Its master data is the only complete description of what the business owns and maintains — and it is almost never in the architecture repository.",
    auth: "OData service user with read-only authorisations, scoped per module.",
    produces: "connector",
    signals: ["sap", "s/4hana", "s4hana", "ecc", "netweaver", "fiori"],
    fingerprints: [
      { kind: "hostname", pattern: "\\bsap[a-z0-9-]*\\.[a-z0-9.-]+\\.[a-z]{2,}\\b", weight: 3, note: "a host named for SAP" },
      { kind: "identifier", pattern: "\\bS/?4\\s?HANA\\b|\\bNetWeaver\\b|\\bFiori\\b|\\bBAPI\\b|\\bIDoc\\b", weight: 3, note: "SAP-only terminology" },
      { kind: "identifier", pattern: "\\b(?:EQUI|IFLOT|AUFK|AFIH|MARA|LFA1|KNA1|BKPF)\\b", weight: 3, note: "an SAP table name" },
      { kind: "identifier", pattern: "\\b(?:IW3[0-9]|ME2[1-3]N|VA0[123]|SE16N?|SM3[0-7])\\b", weight: 3, note: "an SAP transaction code" },
    ],
    scopes: [
      {
        path: "sap/landscape", name: "System landscape", technical: "SLD / LMDB",
        description: "Systems, clients, instances and the transport path between them.",
        yields: ["IT Component", "Environment", "'transports to' relations"],
        enables: "Show the real SAP landscape — dev, QA, production — instead of one box labelled 'SAP'.",
        sensitivity: "internal", volume: "tens of rows",
      },
      {
        path: "sap/pm", name: "Plant Maintenance (PM)", technical: "PM",
        description: "The maintained estate: what exists physically and where it sits.",
        yields: ["Asset", "Location", "Work Order"],
        enables: "Join the physical estate to the applications that manage it.",
        sensitivity: "internal", volume: "100k+ rows",
        children: [
          { path: "sap/pm/equi", name: "Equipment", technical: "EQUI", description: "Every maintained item of equipment, with its class and status.", yields: ["Asset"], enables: "Answer which applications touch which physical assets.", sensitivity: "internal", volume: "~80k rows" },
          { path: "sap/pm/iflot", name: "Functional locations", technical: "IFLOT", description: "The location hierarchy equipment is installed at.", yields: ["Location", "'installed at' relations"], enables: "Roll an outage up from a component to a substation to a region.", sensitivity: "internal", volume: "~20k rows" },
          { path: "sap/pm/aufk", name: "Maintenance orders", technical: "AUFK / AFIH", description: "Work orders against equipment, with dates and cost.", yields: ["Work Order", "'performed on' relations"], enables: "See which assets consume the maintenance budget, and which systems raise the work.", sensitivity: "confidential", volume: "~500k rows" },
        ],
      },
      {
        path: "sap/mm", name: "Materials Management (MM)", technical: "MM",
        description: "Materials, vendors and purchasing.",
        yields: ["Material", "Vendor", "Contract"],
        enables: "Connect supplier risk to the assets and applications that depend on them.",
        sensitivity: "confidential", volume: "50k+ rows",
        children: [
          { path: "sap/mm/mara", name: "Material master", technical: "MARA", description: "Materials and their classification.", yields: ["Material"], sensitivity: "internal", volume: "~40k rows" },
          { path: "sap/mm/lfa1", name: "Vendor master", technical: "LFA1", description: "Suppliers, with their identifiers.", yields: ["Vendor", "'supplied by' relations"], enables: "Ask which systems and assets one supplier failing would touch.", sensitivity: "confidential", volume: "~4k rows" },
        ],
      },
      {
        path: "sap/isu", name: "Utilities (IS-U)", technical: "IS-U",
        description: "Metering, connection objects and the utilities business model.",
        yields: ["Meter", "Connection Object", "Service"],
        enables: "Put the metering chain — device, connection, settlement — on the same graph as the systems that run it.",
        sensitivity: "confidential", volume: "1M+ rows",
      },
      {
        path: "sap/hcm", name: "Human capital (HCM)", technical: "HCM / SuccessFactors",
        description: "Organisational units and reporting lines. People, not payroll.",
        yields: ["Person", "Team", "'reports to' relations"],
        enables: "Give every system a real owner and an org unit that still exists.",
        sensitivity: "personal", volume: "~3k rows",
      },
    ],
  },
  {
    id: "servicenow",
    name: "ServiceNow",
    vendor: "ServiceNow",
    category: "systems",
    status: "planned",
    mode: "api",
    summary: "CMDB configuration items, services and their dependencies.",
    rationale: "The closest thing most organisations have to a live inventory. Its weakness is that it describes operations, not intent — which is exactly the half Nexus adds.",
    auth: "OAuth client with a read-only role, table by table.",
    produces: "connector",
    signals: ["servicenow", "snow", "cmdb", "service-now"],
    fingerprints: [
      { kind: "hostname", pattern: "\\b[a-z0-9-]+\\.service-now\\.com\\b", weight: 4, note: "a ServiceNow instance host" },
      { kind: "identifier", pattern: "\\bcmdb_ci(?:_[a-z_]+)?\\b|\\bcmdb_rel_ci\\b|\\bsys_id\\b", weight: 3, note: "a ServiceNow table or column" },
      { kind: "identifier", pattern: "\\bINC\\d{6,}\\b|\\bCHG\\d{6,}\\b|\\bRITM\\d{6,}\\b", weight: 3, note: "a ServiceNow record number" },
    ],
    scopes: [
      {
        path: "snow/cmdb", name: "CMDB", technical: "cmdb_ci",
        description: "Configuration items and the relationships discovery has mapped.",
        yields: ["IT Component", "Server", "'depends on' relations"],
        enables: "Start from a discovered truth instead of an empty canvas.",
        sensitivity: "internal", volume: "~30k CIs",
        children: [
          { path: "snow/cmdb/ci", name: "Configuration items", technical: "cmdb_ci", description: "Servers, databases, services, appliances.", yields: ["IT Component"], sensitivity: "internal", volume: "~30k rows" },
          { path: "snow/cmdb/rel", name: "CI relationships", technical: "cmdb_rel_ci", description: "Runs on, depends on, hosted by — as discovery found them.", yields: ["relations between IT Components"], enables: "Compare what operations discovered with what architecture believes.", sensitivity: "internal", volume: "~90k rows" },
          { path: "snow/cmdb/apm", name: "Business applications", technical: "cmdb_ci_business_app", description: "The application register, with owners and lifecycle.", yields: ["Application", "Person", "'owns' relations"], enables: "Reconcile the application portfolio against the running estate.", sensitivity: "internal", volume: "~800 rows" },
        ],
      },
      {
        path: "snow/itsm", name: "Incidents & changes", technical: "incident / change_request",
        description: "What broke, what changed, and against which CI.",
        yields: ["Incident", "Change", "'affected' relations"],
        enables: "Weight the architecture by pain: which components generate the incidents.",
        sensitivity: "internal", volume: "~200k rows/year",
      },
    ],
  },
  {
    id: "entra",
    name: "Entra ID",
    vendor: "Microsoft",
    category: "systems",
    status: "planned",
    mode: "api",
    summary: "People, groups and application registrations — ownership, from the source.",
    rationale: "Every SaaS application in use has a registration or a sign-in here. It is the most reliable census of the real application estate, including the parts nobody registered.",
    auth: "Microsoft Graph, application permissions, read-only and consented per scope.",
    produces: "connector",
    signals: ["entra", "azure ad", "active directory", "aad"],
    fingerprints: [
      { kind: "hostname", pattern: "\\blogin\\.microsoftonline\\.com\\b|\\bgraph\\.microsoft\\.com\\b", weight: 4, note: "a Microsoft identity endpoint" },
      { kind: "identifier", pattern: "\\b(?:tenant|client|application)[ _-]?id\\b|\\bservice principal\\b|\\bapp registration\\b", weight: 2, note: "Entra ID terminology" },
    ],
    scopes: [
      { path: "entra/apps", name: "App registrations", technical: "applications", description: "Registered applications and service principals, with their owners.", yields: ["Application", "Person", "'owns' relations"], enables: "Find the applications in use that no register lists — shadow IT, discovered rather than surveyed.", sensitivity: "internal", volume: "~1.2k apps" },
      { path: "entra/groups", name: "Groups", technical: "groups", description: "Security and Microsoft 365 groups, and who is in them.", yields: ["Team", "'member of' relations"], sensitivity: "personal", volume: "~2k groups" },
      { path: "entra/signins", name: "Sign-in activity", technical: "signIns", description: "Which applications are actually used, and how much.", yields: ["usage attributes on Application"], enables: "Retire with evidence: nobody has signed into this in nine months.", sensitivity: "personal", volume: "millions of events" },
    ],
  },
  {
    id: "jira",
    name: "Jira",
    vendor: "Atlassian",
    category: "systems",
    status: "planned",
    mode: "api",
    summary: "Initiatives and epics, so change sits on the same graph as the estate.",
    rationale: "An architecture without the change portfolio is a photograph. This is what makes it a film.",
    auth: "OAuth, project by project.",
    produces: "connector",
    signals: ["jira", "atlassian"],
    fingerprints: [
      { kind: "hostname", pattern: "\\b[a-z0-9-]+\\.atlassian\\.net(?!/wiki)\\b", weight: 4, note: "an Atlassian cloud site" },
      { kind: "identifier", pattern: "\\b[A-Z][A-Z0-9]{1,9}-\\d{1,6}\\b", weight: 2, note: "a Jira issue key" },
    ],
    scopes: [
      { path: "jira/projects", name: "Projects", description: "The projects themselves, with their leads.", yields: ["Project", "Person"], sensitivity: "internal", volume: "~120 projects" },
      { path: "jira/epics", name: "Epics & initiatives", description: "Planned work, with target dates and status.", yields: ["Initiative", "'changes' relations"], enables: "Ask what is scheduled to happen to a system before proposing to change it.", sensitivity: "internal", volume: "~8k issues" },
      { path: "jira/components", name: "Components & labels", description: "How teams name the parts of their systems.", yields: ["candidate IT Components"], enables: "Grow the meta-model from the names engineers already use.", sensitivity: "internal", volume: "~2k values" },
    ],
  },
  {
    id: "confluence",
    name: "Confluence",
    vendor: "Atlassian",
    category: "systems",
    status: "planned",
    mode: "api",
    summary: "Space by space, the pages that describe systems nobody documented elsewhere.",
    rationale: "The unstructured half of the architecture, already written — it only needs reading.",
    auth: "OAuth, space by space.",
    produces: "document",
    signals: ["confluence", "wiki"],
    fingerprints: [
      { kind: "hostname", pattern: "\\b[a-z0-9-]+\\.atlassian\\.net/wiki\\b|\\bconfluence\\.[a-z0-9.-]+\\b", weight: 4, note: "a Confluence site" },
      { kind: "identifier", pattern: "\\b(?:ADR|architecture decision record)\\b", weight: 1, note: "decision records, usually kept in a wiki" },
    ],
    scopes: [
      { path: "confluence/spaces", name: "Named spaces", description: "Specific spaces, chosen one by one.", yields: ["Document", "Application", "Decision"], enables: "Extract the systems and decisions buried in pages, with the page as evidence.", sensitivity: "internal", volume: "per space" },
      { path: "confluence/adr", name: "Decision records", description: "Pages matching an ADR template or label.", yields: ["Decision", "'about' relations"], enables: "A decision log that assembles itself.", sensitivity: "internal", volume: "~300 pages" },
    ],
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    vendor: "Microsoft",
    category: "systems",
    status: "planned",
    mode: "api",
    summary: "Document libraries, including the spreadsheets that are really registries.",
    rationale: "Where the authoritative list usually turns out to live.",
    auth: "Microsoft Graph, site by site.",
    produces: "document",
    signals: ["sharepoint", "onedrive"],
    fingerprints: [
      { kind: "hostname", pattern: "\\b[a-z0-9-]+\\.sharepoint\\.com\\b|\\b[a-z0-9-]+-my\\.sharepoint\\.com\\b", weight: 4, note: "a SharePoint tenant host" },
    ],
    scopes: [
      { path: "sharepoint/sites", name: "Named sites", description: "Specific sites and libraries.", yields: ["Document", "Dataset"], sensitivity: "confidential", volume: "per site" },
      { path: "sharepoint/lists", name: "Lists", description: "SharePoint lists used as registers.", yields: ["Dataset", "typed entities"], enables: "Adopt an existing register without asking anyone to retype it.", sensitivity: "internal", volume: "per list" },
    ],
  },
  {
    id: "ardoq",
    name: "Ardoq / LeanIX",
    vendor: "Ardoq · SAP LeanIX",
    category: "systems",
    status: "planned",
    mode: "api",
    summary: "An existing EA repository, imported rather than retyped.",
    rationale: "Nobody starts from zero. Bringing an incumbent repository in as data — including its meta-model — is the difference between a migration and a rebuild.",
    auth: "API token, read-only.",
    produces: "connector",
    signals: ["ardoq", "leanix", "bizzdesign", "orbus"],
    fingerprints: [
      { kind: "hostname", pattern: "\\b[a-z0-9-]*\\.?ardoq\\.com\\b|\\b[a-z0-9-]+\\.leanix\\.net\\b", weight: 4, note: "an EA repository host" },
      { kind: "identifier", pattern: "\\bcomponent type\\b|\\breference type\\b", weight: 1, note: "EA repository vocabulary" },
    ],
    scopes: [
      { path: "ardoq/components", name: "Components", description: "Every modelled component and its fields.", yields: ["entities of the repository's own kinds"], sensitivity: "internal", volume: "~5k components" },
      { path: "ardoq/references", name: "References", description: "The modelled relationships between them.", yields: ["relations"], sensitivity: "internal", volume: "~15k references" },
      { path: "ardoq/model", name: "Meta-model", description: "Component types, reference types and field definitions.", yields: ["declared node types, relation types and fields"], enables: "Start with the meta-model already agreed, then let it keep evolving here.", sensitivity: "internal", volume: "tens of types" },
    ],
  },

  // ---- code & data platforms ---------------------------------------------------------------
  {
    id: "git",
    name: "Git repositories",
    vendor: "GitHub · GitLab · Azure DevOps",
    category: "repositories",
    status: "planned",
    mode: "api",
    summary: "Services, their manifests and what they call at runtime.",
    rationale: "The only description of the estate that cannot go stale, because the system stops working when it does.",
    auth: "App installation, read-only, organisation or repository scoped.",
    produces: "connector",
    signals: ["github", "gitlab", "azure devops", "bitbucket"],
    fingerprints: [
      { kind: "hostname", pattern: "\\bgithub\\.com\\b|\\bgitlab\\.[a-z0-9.-]+\\b|\\bdev\\.azure\\.com\\b|\\bbitbucket\\.org\\b", weight: 4, note: "a code hosting service" },
      { kind: "file", pattern: "\\b(?:package\\.json|pom\\.xml|build\\.gradle|requirements\\.txt|go\\.mod|Dockerfile|docker-compose\\.ya?ml|\\.tf|helm chart)\\b", weight: 3, note: "a build or deployment manifest" },
    ],
    scopes: [
      { path: "git/repos", name: "Repositories", description: "Names, owners, topics and activity.", yields: ["IT Component", "Team", "'owns' relations"], sensitivity: "internal", volume: "~600 repos" },
      { path: "git/manifests", name: "Manifests & IaC", description: "package.json, pom.xml, Dockerfiles, Terraform, Helm charts.", yields: ["IT Component", "'runs on' and 'depends on' relations"], enables: "Derive the runtime topology from what is actually deployed.", sensitivity: "internal", volume: "~4k files" },
      { path: "git/dependencies", name: "Dependency graph", description: "Libraries and versions, including known vulnerabilities.", yields: ["Library", "Risk"], enables: "Answer which business capabilities a vulnerable library reaches.", sensitivity: "internal", volume: "~50k edges" },
    ],
  },
  {
    id: "databricks",
    name: "Databricks / Snowflake",
    vendor: "Databricks · Snowflake",
    category: "repositories",
    status: "planned",
    mode: "api",
    summary: "Data products, lineage and the pipelines between them.",
    rationale: "Data flow is architecture. Lineage from the platform is the cheapest true integration map an organisation can get.",
    auth: "Service principal with USAGE on named catalogues only.",
    produces: "connector",
    signals: ["databricks", "snowflake", "unity catalog", "delta"],
    fingerprints: [
      { kind: "hostname", pattern: "\\b[a-z0-9-]+\\.(?:cloud\\.databricks\\.com|azuredatabricks\\.net|snowflakecomputing\\.com)\\b", weight: 4, note: "a data platform workspace host" },
      { kind: "identifier", pattern: "\\bunity catalog\\b|\\bdelta (?:lake|table)\\b|\\bwarehouse\\b|\\bmedallion\\b", weight: 2, note: "data platform vocabulary" },
    ],
    scopes: [
      { path: "data/catalog", name: "Catalogues & schemas", description: "The shape of the platform, without reading any rows.", yields: ["Data Product", "Dataset"], sensitivity: "internal", volume: "~40 catalogues" },
      { path: "data/lineage", name: "Table lineage", description: "Which job reads what and writes where.", yields: ["'sends data to' relations"], enables: "Draw the real integration landscape from lineage instead of interviews.", sensitivity: "internal", volume: "~12k edges" },
      { path: "data/jobs", name: "Jobs & pipelines", description: "Scheduled work, with owners and failure history.", yields: ["Pipeline", "Person", "Risk"], sensitivity: "internal", volume: "~900 jobs" },
    ],
  },

  // ---- operations & OT ----------------------------------------------------------------------
  {
    id: "opcua",
    name: "OT historian / OPC UA",
    vendor: "AVEVA PI · Siemens · Kepware",
    category: "operations",
    status: "planned",
    mode: "api",
    summary: "Industrial assets, tags and alarms.",
    rationale: "For an energy or manufacturing business half the estate is here, and it has never appeared in an architecture tool. Reading the asset hierarchy — not the time series — is what puts it on the same graph as everything else.",
    auth: "Read-only OPC UA session or historian API key, namespace by namespace.",
    produces: "connector",
    signals: ["opc", "historian", "pi server", "aveva", "scada", "kepware"],
    fingerprints: [
      { kind: "identifier", pattern: "\\bopc\\.tcp://[\\w\\-.:@/]+", weight: 4, note: "an OPC UA endpoint" },
      { kind: "identifier", pattern: "\\bPI (?:server|system|AF|vision)\\b|\\basset framework\\b|\\bhistorian\\b|\\btag list\\b", weight: 3, note: "historian terminology" },
    ],
    scopes: [
      { path: "ot/assets", name: "Asset hierarchy", description: "The AF/asset model: plants, units, equipment.", yields: ["Asset", "Location", "'part of' relations"], enables: "Put substations and their equipment on the same canvas as the applications that run them.", sensitivity: "internal", volume: "~15k assets" },
      { path: "ot/tags", name: "Tag catalogue", description: "Tag names, units and their asset — the catalogue, not the readings.", yields: ["Signal", "'measured at' relations"], enables: "Trace a metering signal from the sensor to the settlement system.", sensitivity: "internal", volume: "~400k tags" },
      { path: "ot/alarms", name: "Alarms & events", description: "Alarm definitions and history.", yields: ["Risk", "Incident"], sensitivity: "confidential", volume: "millions of events" },
    ],
  },
  {
    id: "scada-ems",
    name: "SCADA / EMS",
    vendor: "Siemens Spectrum · GE · Hitachi",
    category: "operations",
    status: "planned",
    mode: "api",
    summary: "The grid model: what is connected to what, electrically.",
    rationale: "The network model is the ground truth of a grid operator's architecture, and the one model nobody else has.",
    auth: "Read-only export from the model server; never a live control interface.",
    produces: "connector",
    signals: ["scada", "ems", "spectrum", "cim", "network model"],
    fingerprints: [
      { kind: "identifier", pattern: "\\bCGMES\\b|\\bIEC ?61850\\b|\\bIEC ?60870\\b|\\bRTU\\b|\\bnetwork model\\b|\\bbusbar\\b|\\bfeeder\\b", weight: 3, note: "grid operations terminology" },
    ],
    scopes: [
      { path: "scada/model", name: "Network model", technical: "CIM / CGMES", description: "Substations, bays, lines and transformers as modelled.", yields: ["Asset", "'connected to' relations"], enables: "Ask which IT systems an outage in one substation would affect.", sensitivity: "confidential", volume: "~50k elements" },
      { path: "scada/points", name: "Point list", description: "Telemetry points and their mapping to equipment.", yields: ["Signal", "'measured at' relations"], sensitivity: "confidential", volume: "~200k points" },
    ],
  },
];

export const providerById = (id: string): Provider | undefined => PROVIDERS.find((p) => p.id === id);
export const availableProviders = () => PROVIDERS.filter((p) => p.status === "available");
